### ISSUE TITLE
Needs an SSL_upgrade() or start_TLS() method...

### ISSUE THREAD

**Issue by ryanerwin** [jnthn/p6-io-socket-async-ssl#20]
Need a method that upgrades a given stream filehandle into an SSL-wrapped stream (BEGINSSL)
This would be used inside of IMAP, SMTP and other protocols that use BeginTLS once the connection has been established...

For example, Perl 5's IO::Async::SSL provides **SSL_upgrade** to begin TLS. 
Simply "STARTTLS" sounds like a more reasonable name since that what common protocols that use this feature have named it...

**Comment by jnthn** [comment]
This may not be too hard provided we mandate the thing passed in is an `IO::Socket::Async` instance, which is probably reasonable enough given the stated use cases. I'd suggest it's a constructor method a bit like `connect` and `listen`, so something like `IO::Socket::Async::SSL.upgrade($other-some-async-socket)`.

**Comment by jnthn** [comment]
Ended up with `upgrade-client` and `upgrade-server`, so the option arguments passed would match nicely with those passed to `connect` and `listen` respectively. Implemented with some tests and documented.
