### ISSUE TITLE
can't figure out how to write a robust server

### ISSUE THREAD

**Issue by ufobat** [jnthn/p6-io-socket-async-ssl#21]
I am looking for a "HTTPS server" that doesn't terminate as soon as http traffic arrives. 

https://www.nntp.perl.org/group/perl.perl6.users/2017/10/msg4513.html

Maybe the error handling within IO::Socket::Async::SSL is wrong?

**Comment by jnthn** [comment]
Yeah, we'd be better of quietly closing the connection and suppressing those. Done, and tests added.
