### ISSUE TITLE
SSL_CTX_set_default_verify_paths when installing module in Windows 7

### ISSUE THREAD

**Issue by ramiroencinas** [jnthn/p6-io-socket-async-ssl#28]
Windows 7
Rakudo 2017.07
MoarVM 2017.07
Perl 6.c
zef install IO::Socket::Async::SSL
Cannot locate symbol 'SSL_CTX_set_default_verify_paths' in native library ... libeay32.dll

**Comment by winfredraj** [comment]
Same issue while installing Cro::HTTP::Client in Win7 since IO::Socket::Async::SSL is a dependency
2018.10
