### ISSUE TITLE
t/ciphers.t fails on Debian 9

### ISSUE THREAD

**Issue by jantore** [jnthn/p6-io-socket-async-ssl#29]
I fired up the most recent rakudo-star Docker image (based on Debian 9, it seems) to give Cro a whirl, but while installing dependencies IO::Socket::Async::SSL gave me an error during testing.

```
$ zef install IO::Socket::Async::SSL
===> Searching for: IO::Socket::Async::SSL
===> Testing: IO::Socket::Async::SSL:ver<0.6>
# Failed test 'Connection ok when ciphers match up'
# at t/ciphers.t line 26
# error:141640B5:SSL routines:tls_construct_client_hello:no ciphers available
# Looks like you failed 1 test of 2
===> Testing [FAIL]: IO::Socket::Async::SSL:ver<0.6>
Aborting due to test failure: IO::Socket::Async::SSL:ver<0.6> (use --force-test to override)
  in code  at /usr/share/perl6/site/sources/29769DA546CA5B55E3D2F7F8C9D20095C41CCF61 (Zef::Client) line 375
  in method test at /usr/share/perl6/site/sources/29769DA546CA5B55E3D2F7F8C9D20095C41CCF61 (Zef::Client) line 353
  in code  at /usr/share/perl6/site/sources/29769DA546CA5B55E3D2F7F8C9D20095C41CCF61 (Zef::Client) line 530
  in sub  at /usr/share/perl6/site/sources/29769DA546CA5B55E3D2F7F8C9D20095C41CCF61 (Zef::Client) line 527
  in method install at /usr/share/perl6/site/sources/29769DA546CA5B55E3D2F7F8C9D20095C41CCF61 (Zef::Client) line 633
  in sub MAIN at /usr/share/perl6/site/sources/3A2818F8A8CE2F1251F051B779AA0EC17DA2F72E (Zef::CLI) line 152
  in block <unit> at /usr/share/perl6/site/resources/91C74F08994E0006C3049614EF974F6E1A8EDF2D line 1
  in sub MAIN at /usr/share/perl6/site/bin/zef line 2
  in block <unit> at /usr/share/perl6/site/bin/zef line 2
```

Studying `t/ciphers.t`, I see that the cipher set is limited to `NULL-SHA:NULL-MD5`. `openssl ciphers -v -s ALL:eNULL` on various versions of Debian suggests that these were indeed removed in stretch. I have not tested any other distributions.

I suppose naming specific ciphers will likely always be a moving target. One option could be to dynamically choose a few supported ciphers to test with. The easiest solution, however, would probably be using different cipher groups that don't overlap, like `DEFAULT` and `COMPLEMENTOFDEFAULT` or `HIGH` and `MEDIUM`. I tested both of these and they seem to work well.

**Comment by Tyil** [comment]
Can confirm this is broken on latest Debian stable. Tested with docker image `scriptkitties/perl6:2018.01`, running the following commands:

```
docker run -it scriptkitties/perl6:2018.01 sh
apt install libssl-dev
zef install IO::Socket::Async::SSL
```

**Comment by jnthn** [comment]
Hopefully c30cc81 helps; will grab the docker image and try it out later (it needs installing from GitHub, mind; will do a release to CPAN once the fix is verified to help).

**Comment by Tyil** [comment]
```
docker run -it scriptkitties/perl6:2018.01 sh
apt update
apt install libssl-dev
git clone https://github.com/jnthn/p6-io-socket-async-ssl.git
cd p6-io-socket-async-ssl.git
zef install .
```

Installs correctly again:

```
===> Searching for missing dependencies: OpenSSL
===> Testing: OpenSSL:ver<0.1.17>:auth<github:sergot>
# NETWORK_TESTING was not set
# NETWORK_TESTING was not set
===> Testing [OK] for OpenSSL:ver<0.1.17>:auth<github:sergot>
===> Testing: IO::Socket::Async::SSL:ver<0.6>
===> Testing [OK] for IO::Socket::Async::SSL:ver<0.6>
===> Installing: OpenSSL:ver<0.1.17>:auth<github:sergot>
===> Installing: IO::Socket::Async::SSL:ver<0.6>
```

**Comment by jantore** [comment]
Yep, that did the trick. Confirmed working on rakudo-star:2017.10.

**Comment by jnthn** [comment]
Great, thanks for the testing. Version 0.6.1 just uploaded to CPAN.
