### ISSUE TITLE
tests hang with module Toaster

### ISSUE THREAD

**Issue by tbrowder** [jnthn/p6-io-socket-async-ssl#31]
The module hangs when testing with module Toaster and cannot be killed by the job.

However, it does test okay locally with Rakudo 2018.03.

**Comment by jnthn** [comment]
Any information on precisely which test hangs? Though depending on how the toaster copes with malformed output, it may be related to #30, which I just fixed.

**Comment by tbrowder** [comment]
I’ll check and see if I can get more info.

**Comment by tbrowder** [comment]
I got a good run on Toaster with no hangs.
