### ISSUE TITLE
Cpan build readme doesn't link to github

### ISSUE THREAD

**Issue by coke** [jnthn/p6-io-socket-async-ssl#32]
I know in the source repo this would be redundant, but looking at

http://modules.perl6.org/dist/IO::Socket::Async::SSL:cpan:JNTHN

it mentions github at the bottom, but there were no direct links, I had to (gasp) google it to find the repo & the issue tracker.

**Comment by jnthn** [comment]
Linked it; will be in the next version I ship to CPAN. :+1:
