### ISSUE TITLE
IO::Socket::Async::SSL fails tests with OpenSSL 3

### ISSUE THREAD

**Issue by jmaslak** [jnthn/p6-io-socket-async-ssl#69]
I tried to install this module and failed on an Ubuntu 24.04 x64 system, which uses OpenSSL3 (3.0.2).  The P12 file cannot be read by OpenSSL on this system.

I believe the problem is that the RC2 cipher is no longer usable by default in OpenSSL3.

I get the following test failure:

```
jmaslak@resolver2:~/p6-io-socket-async-ssl$ PERL6LIB=lib raku t/client-server.t
ok 1 - listen method returns a Supply
ok 2 - Server not listening until Supply is tapped
ok 3 - Server listens after Supply is tapped
ok 4 - Can establish and SSL connection to the SSL server
ok 5 - Can write to the SSL server
ok 6 - Can get a Supply of incoming data
ok 7 - SSL echo server got back expected data
ok 8 - Can close the SSL server connection
# Subtest: Without specifying a CA, our self-signed server fails verification
    1..2
    ok 1 - code dies
    ok 2 - right exception type (X::IO::Socket::Async::SSL::Verification)
ok 9 - Without specifying a CA, our self-signed server fails verification
ok 10 - Server not listening after tap is closed
# Subtest: When we connect to 127.0.0.1, certificate for localhost will not do
    1..2
    ok 1 - code dies
    ok 2 - right exception type (X::IO::Socket::Async::SSL::Verification)
ok 11 - When we connect to 127.0.0.1, certificate for localhost will not do
ok 12 - socket-host works
ok 13 - Simple server-side ALPN works
ok 14 - Passed protocols are correct
ok 15 - Server-side ALPN with a subroutine works
ok 16 - ALPN on server-side is set
ok 17 - ALPN on server-side is set
ok 18 - Multiple clients with ALPN work
ok 19 - Multiple clients with ALPN work
ok 20 - Negotiation is correct (1)
ok 21 - Negotiation is correct (2)
ok 22 - listen method returns a Supply with PKCS12 bundle
Failed to parse t/certs-and-keys/server-bundle.p12 as PKCS12
  in block  at /home/jmaslak/p6-io-socket-async-ssl/lib/IO/Socket/Async/SSL.pm6 (IO::Socket::Async::SSL) line 508
  in block  at /home/jmaslak/p6-io-socket-async-ssl/lib/IO/Socket/Async/SSL.pm6 (IO::Socket::Async::SSL) line 481
  in block <unit> at t/client-server.t line 171
```

OpenSSL3 on Ubuntu from the command line cannot open the file either.

```
jmaslak@resolver2:~/p6-io-socket-async-ssl$ openssl pkcs12 -info -in t/certs-and-keys/server-bundle.p12
Enter Import Password:
MAC: sha1, Iteration 2048
MAC length: 20, salt length: 8
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 2048
Error outputting keys and certificates
403741A2587F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
```

The problem seems to be the deprecated RC2 cipher.

I believe this problem similar to one seen with a module from our sister language: https://github.com/dsully/perl-crypt-openssl-pkcs12/issues/40

**Comment by jnthn** [comment]
I guess if the cipher is deprecated, the easiest way forward is to remove the test?

**Comment by sdondley** [comment]
Update to my previous update: OpenSSL is installed on the newer machine with openssl@3 but fails to install on my machine with openssl@1.

I'm pretty clueless on ssl libraries except to know it's a mess I keep having for a number of years now. Any specific suggestion on what I should do? Safe to do a --force install?

**Comment by jnthn** [comment]
> [OpenSSL] WARNING: /Users/sean/.rakubrew/versions/moar-2022.06/bin/rakudo is loading libcrypto in an unsafe way

That's tracked in https://github.com/sergot/openssl/issues/81, fwiw.

**Comment by jnthn** [comment]
Having read https://github.com/dsully/perl-crypt-openssl-pkcs12/issues/40#issuecomment-1153148185 it looks like all we may need to do is run `t/certs-and-keys/gencert.sh` on a system with a newer openssl; if anybody experiencing this issue has a chance to clone the module and try that (and even prepare a PR if it works), that would be much appreciated. Otherwise I'll use an Ubuntu 24 container to do it next week.

**Comment by sdondley** [comment]
Yes, running that script from within the t/cert-and-keys fixed one of the failed tests. However, another test is failing: `sh-ciphers.t`. The test just silently dies and returns `(Any)`. Here is the contents of the test file:

```
use Test;
use IO::Socket::Async::SSL;

my constant TEST_PORT = 54335;

my $server = IO::Socket::Async::SSL.listen(
    'localhost', TEST_PORT,
    private-key-file => 't/certs-and-keys/server.key',
    certificate-file => 't/certs-and-keys/server-bundle.crt',
    ciphers => 'DHE-RSA-AES256-GCM-SHA384'
);
my $echo-server-tap = $server.tap: -> $conn {
    $conn.Supply(:bin).tap: -> $data {
        $conn.write($data);
    }
}
END $echo-server-tap.close;

lives-ok
    {
        my $s = await IO::Socket::Async::SSL.connect('localhost', TEST_PORT,
            ca-file => 't/certs-and-keys/ca.crt',
            ciphers => 'DHE-RSA-AES256-GCM-SHA384');
        $s.close;
    },
    'Connection with cipher doing key exchange works';

done-testing;

```

**Comment by sdondley** [comment]
I'm guessing it's the same issue as this one: https://github.com/jnthn/p6-io-socket-async-ssl/issues/68

**Comment by jnthn** [comment]
Regenerated the certificates using an Ubuntu 22.04 container; will make a release.
